service: new-service
useDotenv: true

plugins:
  - serverless-functions-base-path
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-central-1

functions:
  test:
    handler: handlers/index.handler

custom:
  functionsBasePath: src
