service: new-service
useDotenv: true

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-prune-versions

package:
  individually: true

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: eu-central-1

functions:
  test:
    handler: src/handlers/index.handler

custom:
  prune:
    automatic: true
    includeLayers: true
    number: 3
